# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages


before_install:
  - git clone https://github.com/zint/zint.git zint
  - cd zint
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make install